### ISSUE TITLE
Can't connect with server provided by nextcloud music

### ISSUE THREAD

**Issue by on3iro** [austinried/subtracks#18] opened 2021-09-12 07:13 UTC
Hi, this app looks very promising. Unfortunately it does not seem to work with the music app for nextcloud (which runs a subsonic server in the background).
I can't connect to my server. The app _Ultrasonic_ does work however and has one additional server setting, which might fix this (I am very new to subsonic - so no idea if this is the problem).

The setting in Ultrasonic is called: **Force plain password authentication** which seems to circumvent a newer authentication API and sends the password unencrypted (which is fine in this case, as you generally create an app specific token in the nextcloud UI).

Would be great if subtracks could also provide something like this.

Thanks in advance :)

**Comment by austinried** [comment] 2021-09-12 07:35
Interesting, I had seen that option in other players but thought it was just a legacy thing.  Luckily I don't think this will take too much to implement, the subsonic API is pretty clear about using the older auth method.

**Comment by on3iro** [comment] 2021-09-12 07:38
Awesome - thanks for the quick response. The app looks great and I am really looking forward to use it 👍

**Comment by on3iro** [comment] 2021-09-13 06:23
If you want I could take a shot at this. This look like a really good first issue, because it is very limited in scope. (if you are willing to accept contributions :) )

**Comment by austinried** [comment] 2021-09-14 02:38
@on3iro Yeah that would be great actually if you want to do it!  I haven't managed to get a contributing guide up yet but as some general advice I'd say take a look at the `estimateContentLength` flag that's in there for some reference on a similar kind of setting, and also the reference to the Subsonic API info on that is right at the top here: http://www.subsonic.org/pages/api.jsp

**Comment by on3iro** [comment] 2021-09-14 08:30
@austinried great. I will probably be able to start working in this over the next couple of days. I have done quite a lot of react in the past, but haven't worked with react native, yet, so I'll probably need a moment to set everything up :)

**Comment by on3iro** [comment] 2021-09-15 14:27
@austinried I not yet able to run the project, because I am getting a `NullPointerException` from the `Exoplayer`. Do I need to specify a specific JDK when running `yarn android`?

Here's what I did so far:

1. cloned the project
2. setup android studio
3. ran `yarn`
4. initialized the exoplayer submodule
5. ran `yarn start`
6. ran `yarn android` in a separate cli

**Comment by Fr4nzD13trich** [comment] 2021-09-17 22:19
Hi all,

good to hear someones already working on it! Installed it today and it's been driving me crazy for a couple hours since I've always gotten the same response (Connection to .... failed, check settings or server) for whatever I changed on mobile or server.

Nice Job on the layout! I'd be happy if it works as it looks! Best looking Subsonic client so far in my opinion @austinried 

However, I'm experiencing exactly the same issue also via Nextcloud music app

Let me know if I can be of help

Thanks guys,

Fr4nz

**Comment by austinried** [comment] 2021-09-18 01:14
@on3iro Sorry I'm not sure what could be going on there, I tried a fresh clone and couldn't reproduce.  I'm running Ubuntu 20.04 with OpenJDK 11 over here, but it looks like I also have 8 installed.  Could you post the full error you're getting?

**Comment by on3iro** [comment] 2021-09-18 12:25
@austinried Sure thing, I'll have another look tomorrow and will also try out different jdks (I am not quite sure which one I was using lately - so this might already be the issue). If I am unable to resolve the issue I will post the full error log here :)

**Comment by on3iro** [comment] 2021-09-19 04:52
@austinried switching to OpenJDK11 did the trick 👍 .

**Comment by chpio** [comment] 2021-11-12 09:14
To why this option is needed:

> Note: since LMS may store hashed and salted passwords or may forward authentication requests to external services, it cannot handle the token authentication method. You may need to check your client to make sure to use the password authentication method.
> 
> -- https://github.com/epoupon/lms#subsonic-api

Subsonics new authentication api (`t`+`s` params) requires the server to store the password in **clear text**, which is a big NO-NO!

**Comment by austinried** [comment] 2021-12-03 06:24
Closed by #22

**Closed by austinried** 2021-12-03 06:24 UTC
Labels: enhancement

**Comment by litLizard69** [comment] 2021-12-19 18:14
Unfortunately I can't get it to connect to my nextcloud-server. Any fix?

**Comment by 13hannes11** [comment] 2021-12-19 22:00
@litLizard69 for me it works well and I am using the F-Droid version.

**Comment by litLizard69** [comment] 2021-12-20 06:35
> @litLizard69 for me it works well and I am using the F-Droid version.

Oh interesting. Well maybe its just a Problem on my side :D

**Comment by on3iro** [comment] 2021-12-20 08:18
the f-droid version also works fine for me
